-- Synthetic, in-memory fixtures only. This file must never run against Supabase.
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE ROLE service_role;
CREATE SCHEMA cron;
CREATE TABLE cron.job (
  jobid bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  jobname text NOT NULL UNIQUE,
  schedule text NOT NULL,
  command text NOT NULL,
  database text NOT NULL DEFAULT current_database(),
  username text NOT NULL DEFAULT current_user,
  active boolean NOT NULL DEFAULT true
);
-- pg_cron itself is unavailable in PGlite: only its SQL contract is stubbed.
CREATE FUNCTION cron.schedule(job_name text, schedule text, command text)
RETURNS bigint LANGUAGE sql AS $$
  INSERT INTO cron.job(jobname,schedule,command)
  VALUES(job_name,schedule,command) RETURNING jobid;
$$;
CREATE FUNCTION cron.alter_job(
  job_id bigint, schedule text DEFAULT NULL, command text DEFAULT NULL,
  database text DEFAULT NULL, username text DEFAULT NULL, active boolean DEFAULT NULL
) RETURNS void LANGUAGE sql AS $$
  UPDATE cron.job j SET
    schedule=coalesce(alter_job.schedule,j.schedule),
    command=coalesce(alter_job.command,j.command),
    database=coalesce(alter_job.database,j.database),
    username=coalesce(alter_job.username,j.username),
    active=coalesce(alter_job.active,j.active)
  WHERE j.jobid=job_id;
$$;

CREATE TABLE public.finance_realtime_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX finance_realtime_events_created_at_idx ON public.finance_realtime_events(created_at);
CREATE TABLE public.gestao_realtime_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX gestao_realtime_events_created_at_idx ON public.gestao_realtime_events(created_at);
CREATE TABLE public.portal_realtime_signals (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX portal_realtime_signals_created_at_idx ON public.portal_realtime_signals(created_at);
CREATE TABLE public.test_preserved_financial_evidence(id bigint PRIMARY KEY, proof text NOT NULL);
INSERT INTO public.test_preserved_financial_evidence VALUES(1,'synthetic-preserved-proof');
