export const historicalIssueLabels: Record<string, string> = {
  ABSENCE_TOTAL_CONFLICT: 'O total de faltas diverge das marcações de presença.',
  ALL_PRESENCE_BUT_NO_GRADE_OR_RESULT: 'Há presenças, mas a nota e o resultado não foram informados.',
  APPROVED_WITHOUT_FINAL_GRADE: 'O documento informa aprovação sem apresentar a média final.',
  ASSESSMENT_COMPONENTS_PARTIAL_CONFLICT: 'As notas dos instrumentos e a média parcial precisam de conferência.',
  ATTENDANCE_AND_GRADE_ABSENCE_TOTALS_DISAGREE: 'As tabelas de frequência e notas informam totais de faltas diferentes.',
  ATTENDANCE_ASSESSMENT_NAME_DIFFERENCE: 'O nome do aluno difere entre as tabelas de frequência e notas.',
  ATTENDANCE_CONTENT_DATE_CONFLICT: 'A data da frequência difere da data no conteúdo da aula.',
  ATTENDANCE_DATE_WITHOUT_MATCHING_CONTENT: 'Há uma data de frequência sem conteúdo de aula correspondente.',
  BLANK_ASSESSMENT_NOT_ZERO: 'Campo de avaliação em branco; a nota permanece sem registro.',
  CLOSED_BEFORE_LAST_LESSON: 'A data declarada de encerramento é anterior à última aula registrada.',
  CLOSURE_AFTER_LAST_LESSON: 'O encerramento foi declarado depois da última aula registrada.',
  CLOSURE_YEAR_CONFLICT: 'O ano do encerramento precisa de conferência.',
  COMBINED_GRADE_INSTRUMENT: 'O documento combina instrumentos em uma mesma nota; o valor original foi preservado.',
  DAILY_MARKS_DISAGREE_WITH_ATTENDANCE_TOTAL: 'As marcações de frequência divergem do total declarado.',
  DASH_ATTENDANCE_UNDEFINED: 'O traço usado na frequência não tem significado definido no documento.',
  DATE_CONFLICT: 'Há datas conflitantes no documento.',
  DECLARED_PLANNED_AND_GIVEN_DISAGREE: 'As cargas horárias prevista e realizada declaradas são diferentes.',
  FJ_SEMANTICS_NOT_DEFINED_IN_DOCUMENT: 'A marcação FJ não foi definida na legenda do documento.',
  FREQUENCY_PERCENT_CONFLICT: 'O percentual de frequência informado precisa de conferência.',
  GRADE_FORMULA_NOT_DECLARED: 'A fórmula usada para a média não foi declarada no documento.',
  PLANNED_DELIVERED_HOURS_MISMATCH: 'A carga prevista difere das horas de aula registradas.',
  REPEATED_UNQUALIFIED_ASSESSMENT_CATEGORY: 'Há instrumentos avaliativos repetidos, preservados separadamente.',
  REPORTED_ABSENCE_DIFFERS_FROM_F_TIMES_HEADER_HOURS: 'As faltas declaradas divergem das marcações e horas informadas.',
  SOURCE_FREQUENCY_PERCENT_TRUNCATION: 'O percentual escrito parece usar arredondamento diferente e precisa de conferência.',
  SOURCE_HOUR_COLUMNS_DISAGREE_WITH_DECLARED_GIVEN: 'As horas nas colunas das aulas divergem da carga realizada declarada.',
  STUDENT_ATTENDANCE_WITHOUT_GRADE_ROW: 'Há frequência para um aluno sem linha correspondente de notas.',
  STUDENT_NAME_BETWEEN_TABLES: 'O nome do aluno apresenta variação entre tabelas.',
  STUDENT_SUFFIX_D_UNDEFINED: 'O sufixo D no nome do aluno não foi explicado no documento.',
  UNDEFINED_ATTENDANCE_SYMBOL: 'Uma marcação de frequência não está definida na legenda.',
  WEEKDAY_CLASSES_CONFLICT_WITH_PRIOR_GENERAL_SATURDAY_INSTRUCTION: 'O documento registra aulas em dias diferentes do sábado; as datas originais foram preservadas.',
  WEEKDAY_VS_USER_SATURDAY_CONTEXT: 'Os dias de aula registrados precisam ser conferidos com o calendário da turma.',
};
