import {
  BadgeCheck,
  BriefcaseBusiness,
  ClipboardCheck,
  BadgeCheck as CompletionBadge,
  ArrowRightLeft,
  FileBadge,
  FileCheck2,
  Landmark,
  RefreshCcw,
  ScrollText,
} from 'lucide-react';
import { SecretariaDocumentoDefinition } from './secretaria-documentos.types';

export const secretariaDocumentoDefinitions: Record<string, SecretariaDocumentoDefinition> = {
  declaracaoMatricula: {
    id: 'declaracao_matricula',
    title: 'Declaração de Matrícula',
    description: 'Comprovante de vínculo e matrícula ativa na instituição.',
    singularLabel: 'Declaração de Matrícula',
    actionLabel: 'Preparar declaração',
    icon: FileBadge,
    accent: 'text-emerald-700',
    softAccent: 'bg-emerald-50',
    activeEnrollmentOnly: true,
    activeTurmaOnly: true,
  },
  declaracaoFrequencia: {
    id: 'declaracao_frequencia',
    title: 'Declaração de Frequência',
    description: 'Documento de frequência acadêmica consolidada pelo serviço.',
    singularLabel: 'Declaração de Frequência',
    actionLabel: 'Preparar declaração',
    icon: BadgeCheck,
    accent: 'text-sky-700',
    softAccent: 'bg-sky-50',
    activeEnrollmentOnly: true,
    activeTurmaOnly: true,
  },
  boletim: {
    id: 'boletim',
    title: 'Boletim Escolar',
    description: 'Notas, resultados e frequência por aluno ou turma.',
    singularLabel: 'Boletim Escolar',
    actionLabel: 'Preparar boletim',
    icon: ClipboardCheck,
    accent: 'text-indigo-700',
    softAccent: 'bg-indigo-50',
    technicalOnly: true,
    activeEnrollmentOnly: true,
    activeTurmaOnly: true,
    academicPreview: 'boletim_tecnico',
  },
  atestadoConclusao: {
    id: 'atestado_conclusao_tecnico',
    title: 'Atestado de Conclusão',
    description: 'Comprovação provisória de conclusão para estudantes de cursos técnicos.',
    singularLabel: 'Atestado de Conclusão',
    actionLabel: 'Emitir atestado',
    icon: CompletionBadge,
    accent: 'text-emerald-700',
    softAccent: 'bg-emerald-50',
    technicalOnly: true,
    completedOnly: true,
    allowBatch: false,
    academicPreview: 'atestado_conclusao_tecnico',
  },
  declaracaoIrpf: {
    id: 'declaracao_irpf',
    title: 'Declaração de IRPF',
    description: 'Comprovante financeiro anual para fins de Imposto de Renda.',
    singularLabel: 'Declaração de IRPF',
    actionLabel: 'Preparar IRPF',
    icon: Landmark,
    accent: 'text-amber-700',
    softAccent: 'bg-amber-50',
    referenceMode: 'irpf_annual',
  },
  historicoEscolar: {
    id: 'historico_escolar',
    title: 'Histórico Escolar',
    description: 'Percurso acadêmico, componentes, resultados e cargas horárias.',
    singularLabel: 'Histórico Escolar',
    actionLabel: 'Preparar histórico',
    icon: ScrollText,
    accent: 'text-slate-700',
    softAccent: 'bg-slate-100',
    technicalOnly: true,
    enrollmentStatuses: ['ATIVO', 'CONCLUIDO'],
  },
  crachaEstagio: {
    id: 'cracha_estagio',
    title: 'Crachá de Estágio',
    description: 'Identificação do estudante para atividades de estágio.',
    singularLabel: 'Crachá de Estágio',
    actionLabel: 'Preparar crachá',
    icon: FileCheck2,
    accent: 'text-rose-700',
    softAccent: 'bg-rose-50',
    technicalOnly: true,
    activeEnrollmentOnly: true,
    activeTurmaOnly: true,
  },
  rematricula: {
    id: 'rematricula',
    title: 'Rematrícula',
    description: 'Preparação individual ou coletiva do processo de rematrícula.',
    singularLabel: 'Processo de Rematrícula',
    actionLabel: 'Preparar rematrícula',
    icon: RefreshCcw,
    accent: 'text-violet-700',
    softAccent: 'bg-violet-50',
    technicalOnly: true,
    activeEnrollmentOnly: true,
    activeTurmaOnly: true,
  },
  termoEstagio: {
    id: 'termo_estagio',
    title: 'Termo de Estágio',
    description: 'Termo de compromisso e dados acadêmicos do estágio supervisionado.',
    singularLabel: 'Termo de Estágio',
    actionLabel: 'Preparar termo',
    icon: BriefcaseBusiness,
    accent: 'text-teal-700',
    softAccent: 'bg-teal-50',
    technicalOnly: true,
    activeEnrollmentOnly: true,
    activeTurmaOnly: true,
  },
  transferencia: {
    id: 'transferencia',
    title: 'Transferência',
    description: 'Guia de transferência para estudante ativo em turma técnica.',
    singularLabel: 'Transferência',
    actionLabel: 'Preparar transferência',
    icon: ArrowRightLeft,
    accent: 'text-orange-700',
    softAccent: 'bg-orange-50',
    technicalOnly: true,
    activeEnrollmentOnly: true,
    activeTurmaOnly: true,
    allowBatch: false,
  },
};
