import { formatMatricula } from '../../../../lib/academicUtils';

export const buildStudentRegistrationSnapshot = (matricula: any) => ({
  studentName: matricula.parceiros?.nome || '',
  studentSocialName: matricula.parceiros?.nome_social || '',
  studentCpf: matricula.parceiros?.cpf_cnpj || '',
  studentBirthDate: matricula.parceiros?.data_nascimento || '',
  studentPhotoUrl: matricula.parceiros?.foto_url || null,
  studentEmail: matricula.parceiros?.email || '',
  studentPhone: matricula.parceiros?.telefone || '',
  studentSex: matricula.parceiros?.sexo || '',
  studentMaritalStatus: matricula.parceiros?.estado_civil || '',
  studentRaceColor: matricula.parceiros?.raca_cor || '',
  studentRg: matricula.parceiros?.rg || '',
  studentDocumentType: matricula.parceiros?.tipo_documento || '',
  studentRgIssuer: matricula.parceiros?.orgao_emissor || '',
  studentRgState: matricula.parceiros?.rg_uf_emissao || '',
  studentRgIssueDate: matricula.parceiros?.rg_data_emissao || '',
  studentNationality: matricula.parceiros?.nacionalidade || '',
  studentBirthplace: matricula.parceiros?.naturalidade || '',
  studentVoterId: matricula.parceiros?.titulo_eleitor || '',
  studentVoterZone: matricula.parceiros?.titulo_eleitor_zona || '',
  studentVoterSection: matricula.parceiros?.titulo_eleitor_secao || '',
  studentVoterIssueDate: matricula.parceiros?.titulo_eleitor_data_emissao || '',
  studentVoterState: matricula.parceiros?.titulo_eleitor_uf || '',
  studentReservist: matricula.parceiros?.reservista || '',
  studentMotherName: matricula.parceiros?.nome_mae || '',
  studentFatherName: matricula.parceiros?.nome_pai || '',
  highSchoolInstitution: matricula.parceiros?.escola_ensino_medio || '',
  highSchoolCompletionYear: matricula.parceiros?.ano_conclusao_ensino_medio || '',
  studentPcd: matricula.parceiros?.pcd ? 'SIM' : 'NÃO',
  studentPcdType: matricula.parceiros?.pcd_tipo || '',
  studentZipCode: matricula.parceiros?.cep || '',
  studentStreet: matricula.parceiros?.endereco || '',
  studentAddressNumber: matricula.parceiros?.numero || '',
  studentAddressComplement: matricula.parceiros?.complemento || '',
  studentDistrict: matricula.parceiros?.bairro || '',
  studentCity: matricula.parceiros?.cidade || '',
  studentState: matricula.parceiros?.uf || '',
  studentResponsibleName: matricula.parceiros?.responsavel_nome || '',
  studentResponsibleCpf: matricula.parceiros?.responsavel_cpf || '',
  studentResponsibleRelation: matricula.parceiros?.responsavel_parentesco || '',
  studentResponsiblePhone: matricula.parceiros?.responsavel_telefone || '',
  studentNotes: matricula.parceiros?.observacao || '',
  studentMatricula: formatMatricula(
    matricula.id,
    matricula.data_matricula,
    matricula.turmas?.polo_id
  ),
  courseName: matricula.turmas?.cursos?.nome || '',
  courseModality: matricula.turmas?.cursos?.modalidade || '',
  courseHours: Number(matricula.turmas?.cursos?.carga_horaria || 0),
  courseArea: matricula.turmas?.cursos?.area || '',
  courseTechnologicalAxis: matricula.turmas?.cursos?.eixo_tecnologico || '',
  courseProfessionalProfile: matricula.turmas?.cursos?.perfil_profissional_conclusao || '',
  courseStartDate: matricula.turmas?.data_inicio || '',
  classShift: matricula.turmas?.turno || '',
  className: matricula.turmas?.nome || '',
  unitName: matricula.turmas?.polos?.nome || '',
  enrollmentStatus: matricula.status || '',
  enrollmentDate: matricula.data_matricula || '',
});

