import { createDocumentTemplateService } from '../shared/document-template.service';

export const atestadoConclusaoService = createDocumentTemplateService('atestado_conclusao_tecnico', {
  textContent: `<p>Atestamos, para os devidos fins, que o(a) aluno(a) <b>{{ALUNO_NOME}}</b>, CPF nº <b>{{ALUNO_CPF}}</b>, matrícula nº <b>{{ALUNO_MATRICULA}}</b>, concluiu integralmente o curso técnico de <b>{{CURSO_NOME}}</b>, turma <b>{{TURMA_NOME}}</b>, com carga horária total de <b>{{CARGA_HORARIA_TOTAL}}</b> horas.</p><br><p>A conclusão ocorreu em <b>{{DATA_CONCLUSAO}}</b>, tendo o(a) estudante cumprido os componentes curriculares e requisitos acadêmicos previstos para a formação técnica.</p><br><p>O presente atestado é emitido a pedido do(a) interessado(a) para comprovação provisória de conclusão, até a expedição do diploma ou certificado definitivo.</p>`,
  absoluteFields: [
    {
      id: 'atestado_data',
      type: 'text',
      value: '{{CIDADE_POLO}}, {{DATA_ATUAL}}',
      x: 420,
      y: 790,
      width: 300,
      style: { textAlign: 'right', fontWeight: 'bold', fontSize: '13px' },
    },
    {
      id: 'atestado_assinatura',
      type: 'text',
      value: '___________________________________________\nSecretaria Acadêmica',
      x: 235,
      y: 900,
      width: 325,
      style: { textAlign: 'center', fontSize: '13px', whiteSpace: 'pre-line' },
    },
    {
      id: 'atestado_footer_valid_until',
      type: 'text',
      value: 'ESTE DOCUMENTO É VÁLIDO ATÉ <span style="color: #ef4444">{{VALIDADE_DATA}}</span>.',
      x: 50,
      y: 975,
      width: 694,
      style: { textAlign: 'center', fontSize: '9px', color: '#000000', fontWeight: 'bold', textTransform: 'uppercase' },
    },
    {
      id: 'atestado_footer_url',
      type: 'text',
      value: 'PARA VERIFICAR A AUTENTICIDADE DESTE DOCUMENTO ACESSE: <span style="color: #ef4444">WWW.UNIVERSOCC.COM.BR/VALIDADOR</span>',
      x: 50,
      y: 995,
      width: 694,
      style: { textAlign: 'center', fontSize: '9px', color: '#000000', fontWeight: 'bold', textTransform: 'uppercase' },
    },
    {
      id: 'atestado_footer_validity',
      type: 'text',
      value: 'VALIDADE DESTE DOCUMENTO: <span style="color: #ef4444">{{VALIDADE_DIAS}} DIAS A PARTIR DA DATA DE EMISSÃO</span>.',
      x: 50,
      y: 1015,
      width: 694,
      style: { textAlign: 'center', fontSize: '9px', color: '#000000', fontWeight: 'bold', textTransform: 'uppercase' },
    },
    {
      id: 'atestado_footer_generation',
      type: 'text',
      value: 'DOCUMENTO GERADO EM: {{DATA_GERACAO}}',
      x: 50,
      y: 1035,
      width: 694,
      style: { textAlign: 'center', fontSize: '8px', color: '#94a3b8', textTransform: 'uppercase' },
    },
  ],
  validityDays: 90,
  v: 2,
});
