CREATE TABLE IF NOT EXISTS public.finance_realtime_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_table text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('INSERT', 'UPDATE', 'DELETE')),
  entity_id uuid NOT NULL,
  polo_id uuid,
  aluno_id uuid,
  turma_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS finance_realtime_events_created_at_idx
  ON public.finance_realtime_events (created_at);
CREATE INDEX IF NOT EXISTS finance_realtime_events_polo_id_idx
  ON public.finance_realtime_events (polo_id, id DESC);
CREATE INDEX IF NOT EXISTS finance_realtime_events_aluno_id_idx
  ON public.finance_realtime_events (aluno_id, id DESC);

ALTER TABLE public.finance_realtime_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS finance_realtime_events_select ON public.finance_realtime_events;
CREATE POLICY finance_realtime_events_select
  ON public.finance_realtime_events
  FOR SELECT
  TO authenticated
  USING (
    (
      aluno_id IS NOT NULL
      AND aluno_id = public.current_aluno_id()
    )
    OR (
      (
        (polo_id IS NULL AND public.is_gestor_global())
        OR (polo_id IS NOT NULL AND public.is_gestor_for_polo(polo_id))
      )
      AND (
        public.gestor_has_financeiro_tab('resumo')
        OR public.gestor_has_financeiro_tab('receber')
        OR public.gestor_has_tab('secretaria', 'recebimentos')
      )
    )
  );

CREATE OR REPLACE FUNCTION public.emit_finance_realtime_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.contas_receber;
  v_event_id bigint;
BEGIN
  v_row := CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;

  INSERT INTO public.finance_realtime_events (
    source_table,
    event_type,
    entity_id,
    polo_id,
    aluno_id,
    turma_id
  )
  VALUES (
    TG_TABLE_NAME,
    TG_OP,
    v_row.id,
    v_row.polo_id,
    v_row.cliente_id,
    v_row.turma_id
  )
  RETURNING id INTO v_event_id;

  IF v_event_id % 100 = 0 THEN
    DELETE FROM public.finance_realtime_events
    WHERE created_at < now() - interval '24 hours';
  END IF;

  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS contas_receber_emit_realtime_event ON public.contas_receber;
CREATE TRIGGER contas_receber_emit_realtime_event
AFTER INSERT OR UPDATE OR DELETE ON public.contas_receber
FOR EACH ROW
EXECUTE FUNCTION public.emit_finance_realtime_event();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'finance_realtime_events'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.finance_realtime_events;
  END IF;
END;
$$;

REVOKE ALL ON TABLE public.finance_realtime_events FROM anon, authenticated;
GRANT SELECT ON TABLE public.finance_realtime_events TO authenticated;
REVOKE ALL ON FUNCTION public.emit_finance_realtime_event() FROM PUBLIC, anon, authenticated;
