-- DADO GERADO: países/ISO do IBGE e gentílicos curados em pt-BR.
-- Fonte: https://servicodados.ibge.gov.br/api/v1/localidades/paises?orderBy=nome
-- Sem gentílico revisado, nacionalidade fica NULL e o cadastro aceita texto livre.

INSERT INTO public.catalogo_paises_nacionalidades (
  codigo_iso3, codigo_iso2, codigo_m49, pais, nacionalidade
) VALUES
  ('AFG', 'AF', 4, 'Afeganistão', NULL),
  ('ZAF', 'ZA', 710, 'África do Sul', 'SUL-AFRICANA'),
  ('ALB', 'AL', 8, 'Albânia', 'ALBANESA'),
  ('DEU', 'DE', 276, 'Alemanha', 'ALEMÃ'),
  ('AND', 'AD', 20, 'Andorra', 'ANDORRANA'),
  ('AGO', 'AO', 24, 'Angola', 'ANGOLANA'),
  ('ATG', 'AG', 28, 'Antígua e Barbuda', NULL),
  ('SAU', 'SA', 682, 'Arábia Saudita', NULL),
  ('DZA', 'DZ', 12, 'Argélia', NULL),
  ('ARG', 'AR', 32, 'Argentina', 'ARGENTINA'),
  ('ARM', 'AM', 51, 'Armênia', NULL),
  ('AUS', 'AU', 36, 'Austrália', 'AUSTRALIANA'),
  ('AUT', 'AT', 40, 'Áustria', 'AUSTRÍACA'),
  ('AZE', 'AZ', 31, 'Azerbaijão', NULL),
  ('BHS', 'BS', 44, 'Bahamas', NULL),
  ('BGD', 'BD', 50, 'Bangladesh', NULL),
  ('BRB', 'BB', 52, 'Barbados', NULL),
  ('BHR', 'BH', 48, 'Barein', NULL),
  ('BLR', 'BY', 112, 'Belarus', NULL),
  ('BEL', 'BE', 56, 'Bélgica', NULL),
  ('BLZ', 'BZ', 84, 'Belize', NULL),
  ('BEN', 'BJ', 204, 'Benin', NULL),
  ('BOL', 'BO', 68, 'Bolívia', 'BOLIVIANA'),
  ('BIH', 'BA', 70, 'Bósnia e Herzegovina', NULL),
  ('BWA', 'BW', 72, 'Botsuana', NULL),
  ('BRA', 'BR', 76, 'Brasil', 'BRASILEIRA'),
  ('BRN', 'BN', 96, 'Brunei', NULL),
  ('BGR', 'BG', 100, 'Bulgária', NULL),
  ('BFA', 'BF', 854, 'Burkina Faso', NULL),
  ('BDI', 'BI', 108, 'Burundi', NULL),
  ('BTN', 'BT', 64, 'Butão', NULL),
  ('CPV', 'CV', 132, 'Cabo Verde', 'CABO-VERDIANA'),
  ('CMR', 'CM', 120, 'Camarões', NULL),
  ('KHM', 'KH', 116, 'Camboja', NULL),
  ('CAN', 'CA', 124, 'Canadá', 'CANADENSE'),
  ('QAT', 'QA', 634, 'Catar', NULL),
  ('KAZ', 'KZ', 398, 'Cazaquistão', NULL),
  ('TCD', 'TD', 148, 'Chade', NULL),
  ('CHL', 'CL', 152, 'Chile', 'CHILENA'),
  ('CHN', 'CN', 156, 'China', 'CHINESA'),
  ('CYP', 'CY', 196, 'Chipre', NULL),
  ('COL', 'CO', 170, 'Colômbia', 'COLOMBIANA'),
  ('COM', 'KM', 174, 'Comores', NULL),
  ('CIV', 'CI', 384, 'Costa do Marfim', NULL),
  ('CRI', 'CR', 188, 'Costa Rica', NULL),
  ('HRV', 'HR', 191, 'Croácia', NULL),
  ('CUB', 'CU', 192, 'Cuba', 'CUBANA'),
  ('DNK', 'DK', 208, 'Dinamarca', NULL),
  ('DJI', 'DJ', 262, 'Djibouti', NULL),
  ('DMA', 'DM', 212, 'Dominica', NULL),
  ('EGY', 'EG', 818, 'Egito', NULL),
  ('SLV', 'SV', 222, 'El Salvador', NULL),
  ('ARE', 'AE', 784, 'Emirados Árabes Unidos', NULL),
  ('ECU', 'EC', 218, 'Equador', 'EQUATORIANA'),
  ('ERI', 'ER', 232, 'Eritreia', NULL),
  ('SVK', 'SK', 703, 'Eslováquia', NULL),
  ('SVN', 'SI', 705, 'Eslovênia', NULL),
  ('ESP', 'ES', 724, 'Espanha', 'ESPANHOLA'),
  ('USA', 'US', 840, 'Estados Unidos da América', 'ESTADUNIDENSE'),
  ('EST', 'EE', 233, 'Estônia', NULL),
  ('SWZ', 'SZ', 748, 'Eswatini', NULL),
  ('ETH', 'ET', 231, 'Etiópia', NULL),
  ('FJI', 'FJ', 242, 'Fiji', NULL),
  ('PHL', 'PH', 608, 'Filipinas', NULL),
  ('FIN', 'FI', 246, 'Finlândia', NULL),
  ('FRA', 'FR', 250, 'França', 'FRANCESA'),
  ('GAB', 'GA', 266, 'Gabão', NULL),
  ('GMB', 'GM', 270, 'Gâmbia', NULL),
  ('GHA', 'GH', 288, 'Gana', NULL),
  ('GEO', 'GE', 268, 'Geórgia', NULL),
  ('GRD', 'GD', 308, 'Granada', NULL),
  ('GRC', 'GR', 300, 'Grécia', NULL),
  ('GTM', 'GT', 320, 'Guatemala', NULL),
  ('GUY', 'GY', 328, 'Guiana', NULL),
  ('GIN', 'GN', 324, 'Guiné', NULL),
  ('GNQ', 'GQ', 226, 'Guiné Equatorial', NULL),
  ('GNB', 'GW', 624, 'Guiné-Bissau', 'GUINEENSE'),
  ('HTI', 'HT', 332, 'Haiti', 'HAITIANA'),
  ('HND', 'HN', 340, 'Honduras', NULL),
  ('HUN', 'HU', 348, 'Hungria', NULL),
  ('YEM', 'YE', 887, 'Iêmen', NULL),
  ('MHL', 'MH', 584, 'Ilhas Marshall', NULL),
  ('SLB', 'SB', 90, 'Ilhas Salomão', NULL),
  ('IND', 'IN', 356, 'Índia', NULL),
  ('IDN', 'ID', 360, 'Indonésia', NULL),
  ('IRN', 'IR', 364, 'Irã', NULL),
  ('IRQ', 'IQ', 368, 'Iraque', NULL),
  ('IRL', 'IE', 372, 'Irlanda', NULL),
  ('ISL', 'IS', 352, 'Islândia', NULL),
  ('ISR', 'IL', 376, 'Israel', NULL),
  ('ITA', 'IT', 380, 'Itália', 'ITALIANA'),
  ('JAM', 'JM', 388, 'Jamaica', NULL),
  ('JPN', 'JP', 392, 'Japão', 'JAPONESA'),
  ('JOR', 'JO', 400, 'Jordânia', NULL),
  ('KIR', 'KI', 296, 'Kiribati', NULL),
  ('KWT', 'KW', 414, 'Kuwait', NULL),
  ('LAO', 'LA', 418, 'Laos', NULL),
  ('LSO', 'LS', 426, 'Lesoto', NULL),
  ('LVA', 'LV', 428, 'Letônia', NULL),
  ('LBN', 'LB', 422, 'Líbano', NULL),
  ('LBR', 'LR', 430, 'Libéria', NULL),
  ('LBY', 'LY', 434, 'Líbia', NULL),
  ('LIE', 'LI', 438, 'Liechtenstein', NULL),
  ('LTU', 'LT', 440, 'Lituânia', NULL),
  ('LUX', 'LU', 442, 'Luxemburgo', NULL),
  ('MKD', 'MK', 807, 'Macedônia do Norte', NULL),
  ('MDG', 'MG', 450, 'Madagascar', NULL),
  ('MYS', 'MY', 458, 'Malásia', NULL),
  ('MWI', 'MW', 454, 'Malauí', NULL),
  ('MDV', 'MV', 462, 'Maldivas', NULL),
  ('MLI', 'ML', 466, 'Mali', NULL),
  ('MLT', 'MT', 470, 'Malta', NULL),
  ('MAR', 'MA', 504, 'Marrocos', NULL),
  ('MUS', 'MU', 480, 'Maurício', NULL),
  ('MRT', 'MR', 478, 'Mauritânia', NULL),
  ('MEX', 'MX', 484, 'México', 'MEXICANA'),
  ('MMR', 'MM', 104, 'Mianmar', NULL),
  ('FSM', 'FM', 583, 'Micronésia', NULL),
  ('MOZ', 'MZ', 508, 'Moçambique', 'MOÇAMBICANA'),
  ('MDA', 'MD', 498, 'Moldávia', NULL),
  ('MCO', 'MC', 492, 'Mônaco', NULL),
  ('MNG', 'MN', 496, 'Mongólia', NULL),
  ('MNE', 'ME', 499, 'Montenegro', NULL),
  ('NAM', 'NA', 516, 'Namíbia', NULL),
  ('NRU', 'NR', 520, 'Nauru', NULL),
  ('NPL', 'NP', 524, 'Nepal', NULL),
  ('NIC', 'NI', 558, 'Nicarágua', NULL),
  ('NER', 'NE', 562, 'Niger', NULL),
  ('NGA', 'NG', 566, 'Nigéria', NULL),
  ('NOR', 'NO', 578, 'Noruega', NULL),
  ('NZL', 'NZ', 554, 'Nova Zelândia', NULL),
  ('OMN', 'OM', 512, 'Omã', NULL),
  ('NLD', 'NL', 528, 'Países Baixos', NULL),
  ('PLW', 'PW', 585, 'Palau', NULL),
  ('PAN', 'PA', 591, 'Panamá', NULL),
  ('PNG', 'PG', 598, 'Papua Nova Guiné', NULL),
  ('PAK', 'PK', 586, 'Paquistão', NULL),
  ('PRY', 'PY', 600, 'Paraguai', 'PARAGUAIA'),
  ('PER', 'PE', 604, 'Peru', 'PERUANA'),
  ('POL', 'PL', 616, 'Polônia', NULL),
  ('PRT', 'PT', 620, 'Portugal', 'PORTUGUESA'),
  ('KEN', 'KE', 404, 'Quênia', NULL),
  ('KGZ', 'KG', 417, 'Quirguistão', NULL),
  ('GBR', 'GB', 826, 'Reino Unido', 'BRITÂNICA'),
  ('CAF', 'CF', 140, 'República Centro-Africana', NULL),
  ('KOR', 'KR', 410, 'República da Coreia', NULL),
  ('COD', 'CD', 180, 'República Democrática do Congo', NULL),
  ('COG', 'CG', 178, 'República do Congo', NULL),
  ('DOM', 'DO', 214, 'República Dominicana', NULL),
  ('PRK', 'KP', 408, 'República Popular Democrática da Coreia', NULL),
  ('CZE', 'CZ', 203, 'República Tcheca', NULL),
  ('ROU', 'RO', 642, 'Romênia', NULL),
  ('RWA', 'RW', 646, 'Ruanda', NULL),
  ('RUS', 'RU', 643, 'Rússia (Federação Russa)', 'RUSSA'),
  ('WSM', 'WS', 882, 'Samoa', NULL),
  ('SMR', 'SM', 674, 'San Marino', NULL),
  ('LCA', 'LC', 662, 'Santa Lúcia', NULL),
  ('KNA', 'KN', 659, 'São Cristóvão e Nevis', NULL),
  ('STP', 'ST', 678, 'São Tomé e Príncipe', 'SÃO-TOMENSE'),
  ('VCT', 'VC', 670, 'São Vicente e Granadinas', NULL),
  ('SYC', 'SC', 690, 'Seichelles', NULL),
  ('SEN', 'SN', 686, 'Senegal', NULL),
  ('SLE', 'SL', 694, 'Serra Leoa', NULL),
  ('SRB', 'RS', 688, 'Sérvia', NULL),
  ('SGP', 'SG', 702, 'Singapura', NULL),
  ('SYR', 'SY', 760, 'Síria', NULL),
  ('SOM', 'SO', 706, 'Somália', NULL),
  ('LKA', 'LK', 144, 'Sri Lanka', NULL),
  ('SDN', 'SD', 729, 'Sudão', NULL),
  ('SSD', 'SS', 728, 'Sudão do Sul', NULL),
  ('SWE', 'SE', 752, 'Suécia', NULL),
  ('CHE', 'CH', 756, 'Suíça', 'SUÍÇA'),
  ('SUR', 'SR', 740, 'Suriname', NULL),
  ('TJK', 'TJ', 762, 'Tadjiquistão', NULL),
  ('THA', 'TH', 764, 'Tailândia', NULL),
  ('TZA', 'TZ', 834, 'Tanzânia', NULL),
  ('TLS', 'TL', 626, 'Timor-Leste', 'TIMORENSE'),
  ('TGO', 'TG', 768, 'Togo', NULL),
  ('TON', 'TO', 776, 'Tonga', NULL),
  ('TTO', 'TT', 780, 'Trinidad e Tobago', NULL),
  ('TUN', 'TN', 788, 'Tunísia', NULL),
  ('TKM', 'TM', 795, 'Turcomenistão', NULL),
  ('TUR', 'TR', 792, 'Turquia', NULL),
  ('TUV', 'TV', 798, 'Tuvalu', NULL),
  ('UKR', 'UA', 804, 'Ucrânia', NULL),
  ('UGA', 'UG', 800, 'Uganda', NULL),
  ('URY', 'UY', 858, 'Uruguai', 'URUGUAIA'),
  ('UZB', 'UZ', 860, 'Uzbequistão', NULL),
  ('VUT', 'VU', 548, 'Vanuatu', NULL),
  ('VEN', 'VE', 862, 'Venezuela', 'VENEZUELANA'),
  ('VNM', 'VN', 704, 'Vietnã', NULL),
  ('ZMB', 'ZM', 894, 'Zâmbia', NULL),
  ('ZWE', 'ZW', 716, 'Zimbábue', NULL)
ON CONFLICT (codigo_iso3) DO UPDATE SET
  codigo_iso2 = EXCLUDED.codigo_iso2,
  codigo_m49 = EXCLUDED.codigo_m49,
  pais = EXCLUDED.pais,
  nacionalidade = EXCLUDED.nacionalidade,
  ativo = true,
  atualizado_em = now();
