import React from 'react';
import { AlignCenter, AlignJustify, AlignLeft, AlignRight, FileText, Image, Loader2, Palette, Trash2, Upload } from 'lucide-react';
import type { CarteirinhaEditorPanelProps } from './carteirinha-editor.types';

const CarteirinhaEditorBackIdentityPanel: React.FC<CarteirinhaEditorPanelProps> = ({
  formData,
  handleChange,
  handleUploadFile,
  isUploading,
  setFormData,
}) => (
  <>
    <div className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50/50 p-4">
      <h4 className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#001a33]"><Palette size={14} className="text-pink-600" />Estilização do Verso</h4>
      <div><label className="mb-1.5 flex justify-between text-[10px] font-bold uppercase tracking-widest text-slate-500"><span>Cor das Fontes (Verso)</span><span className="font-mono">{formData.corTextoVerso || '#1e293b'}</span></label><input type="color" name="corTextoVerso" value={formData.corTextoVerso || '#1e293b'} onChange={handleChange} className="h-9 w-full cursor-pointer rounded-xl border border-slate-200 bg-white p-1" /></div>
    </div>

    <div className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50/50 p-4">
      <h4 className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#001a33]"><Image size={14} className="text-pink-600" />Imagem de Fundo (Verso)</h4>
      <div className="flex gap-2"><input type="text" name="bgVersoUrl" placeholder="URL da imagem de fundo (.png / .jpg)" value={formData.bgVersoUrl || ''} onChange={handleChange} className="flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-bold text-slate-700 outline-none transition-all focus:border-pink-500 focus:bg-white" /><label className="relative flex shrink-0 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white p-3 transition-colors hover:bg-pink-50 hover:text-pink-600"><input type="file" accept="image/*" onChange={(event) => handleUploadFile(event, 'bgVersoUrl')} className="absolute inset-0 cursor-pointer opacity-0" disabled={isUploading} />{isUploading ? <Loader2 size={18} className="animate-spin text-pink-600" /> : <Upload size={18} />}</label></div>
      <p className="text-[9px] font-bold uppercase leading-normal tracking-widest text-slate-400">Recomendado: 856 x 540 pixels (.png)</p>
    </div>

    <div className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50/50 p-4">
      <div className="flex items-center justify-between"><h4 className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#001a33]"><FileText size={14} className="text-pink-600" />Regras e Legislação</h4><label className="relative inline-flex cursor-pointer items-center"><input type="checkbox" name="showTextoVerso" checked={formData.showTextoVerso !== false} onChange={handleChange} className="peer sr-only" /><div className="h-5 w-9 rounded-full bg-slate-200 after:absolute after:left-[2px] after:top-[2px] after:h-4 after:w-4 after:rounded-full after:border after:border-slate-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-pink-600 peer-checked:after:translate-x-full peer-checked:after:border-white" /></label></div>
      {formData.showTextoVerso !== false && <><textarea name="textoVerso" value={formData.textoVerso} onChange={handleChange} className="min-h-[100px] w-full resize-y rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-bold text-slate-700 outline-none transition-all custom-scrollbar focus:border-pink-500 focus:bg-white" placeholder="Instruções e leis de meia-entrada" /><div className="mt-2 flex items-center gap-1.5">{(['left', 'center', 'right', 'justify'] as const).map((align) => { const Icon = align === 'left' ? AlignLeft : align === 'center' ? AlignCenter : align === 'right' ? AlignRight : AlignJustify; return <button key={align} type="button" onClick={() => setFormData({ ...formData, alinhamentoTextoVerso: align })} className={`rounded-lg border p-2 transition-all ${formData.alinhamentoTextoVerso === align || (!formData.alinhamentoTextoVerso && align === 'center') ? 'border-pink-300 bg-pink-50 text-pink-600' : 'border-slate-200 bg-white text-slate-500 hover:text-slate-700'}`} title={align.toUpperCase()}><Icon size={14} /></button>; })}</div><div className="mt-2.5"><label className="mb-1 flex justify-between text-[9px] font-bold uppercase tracking-widest text-slate-500"><span>Tamanho Fonte</span><span className="font-mono">{(formData.tamanhoFonteVerso || 5).toFixed(1)}px</span></label><input type="range" name="tamanhoFonteVerso" min="3" max="9" step="0.2" value={formData.tamanhoFonteVerso || 5} onChange={(event) => setFormData({ ...formData, tamanhoFonteVerso: Number.parseFloat(event.target.value) })} className="h-1 w-full cursor-pointer appearance-none rounded-lg bg-slate-250 accent-pink-600" /></div></>}
    </div>

    <div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50/50 p-4"><div><h4 className="text-xs font-black uppercase tracking-widest text-[#001a33]">Local de Assinatura do Aluno</h4><p className="mt-0.5 text-[9px] font-bold uppercase tracking-widest text-slate-400">Habilita a linha para assinatura física do aluno</p></div><label className="relative inline-flex cursor-pointer items-center"><input type="checkbox" name="showAssinaturaAluno" checked={formData.showAssinaturaAluno !== false} onChange={handleChange} className="peer sr-only" /><div className="h-5 w-9 rounded-full bg-slate-200 after:absolute after:left-[2px] after:top-[2px] after:h-4 after:w-4 after:rounded-full after:border after:border-slate-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-pink-600 peer-checked:after:translate-x-full peer-checked:after:border-white" /></label></div>

    <div className="space-y-4 rounded-2xl border border-slate-200 bg-slate-50/50 p-4">
      <div className="flex items-center justify-between"><div><h4 className="text-xs font-black uppercase tracking-widest text-[#001a33]">Assinatura do Diretor/Gestor</h4><p className="mt-0.5 text-[9px] font-bold uppercase tracking-widest text-slate-400">Mostra linha e imagem da assinatura do diretor</p></div><label className="relative inline-flex cursor-pointer items-center"><input type="checkbox" name="showAssinaturaDiretor" checked={formData.showAssinaturaDiretor !== false} onChange={handleChange} className="peer sr-only" /><div className="h-5 w-9 rounded-full bg-slate-200 after:absolute after:left-[2px] after:top-[2px] after:h-4 after:w-4 after:rounded-full after:border after:border-slate-300 after:bg-white after:transition-all after:content-[''] peer-checked:bg-pink-600 peer-checked:after:translate-x-full peer-checked:after:border-white" /></label></div>
      {formData.showAssinaturaDiretor !== false && (
        <div className="space-y-3 border-t border-slate-100 pt-2">
          <div><label className="mb-1.5 block text-[10px] font-bold uppercase tracking-widest text-slate-500">Cargo / Título do Gestor</label><input type="text" name="textoDiretor" value={formData.textoDiretor} onChange={handleChange} placeholder="Ex: Assinatura do Diretor(a)" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 outline-none transition-all focus:border-pink-500 focus:bg-white" /></div>
          <div><label className="mb-1.5 block text-[10px] font-bold uppercase tracking-widest text-slate-500">Origem da Assinatura</label><select name="assinaturaOrigem" value={formData.assinaturaOrigem || 'none'} onChange={handleChange} className="w-full cursor-pointer rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 outline-none transition-all focus:border-pink-500"><option value="none">Nenhuma Assinatura</option><option value="diretoriaGeral">Diretoria Geral (Configurações)</option><option value="secretaria">Secretaria (Configurações)</option><option value="coordenacao">Coordenação (Configurações)</option><option value="financeiro">Financeiro (Configurações)</option><option value="manual">Upload Manual / URL Personalizada</option></select></div>
          {formData.assinaturaOrigem === 'manual' && <div><label className="mb-1.5 block text-[10px] font-bold uppercase tracking-widest text-slate-500">Upload da Assinatura PNG</label><div className="flex gap-2"><input type="text" name="assinaturaDiretorPngUrl" placeholder="URL da assinatura digitalizada (.png)" value={formData.assinaturaDiretorPngUrl || ''} onChange={handleChange} className="flex-1 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 outline-none transition-all focus:border-pink-500 focus:bg-white" />{formData.assinaturaDiretorPngUrl && <button type="button" onClick={() => setFormData({ ...formData, assinaturaDiretorPngUrl: '' })} className="shrink-0 rounded-xl border border-red-200 bg-red-50 p-2.5 text-red-500 transition-colors hover:bg-red-100" title="Excluir Assinatura"><Trash2 size={16} /></button>}<label className="relative flex shrink-0 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white p-2.5 transition-colors hover:bg-pink-50 hover:text-pink-600"><input type="file" accept="image/*" onChange={(event) => handleUploadFile(event, 'assinaturaDiretorPngUrl')} className="absolute inset-0 cursor-pointer opacity-0" disabled={isUploading} />{isUploading ? <Loader2 size={16} className="animate-spin text-pink-600" /> : <Upload size={16} />}</label></div><p className="mt-1 text-[9px] font-bold uppercase tracking-widest text-slate-400">Recomendado: PNG com fundo transparente</p></div>}
          {formData.assinaturaOrigem && formData.assinaturaOrigem !== 'none' && <div className="space-y-3"><div className="flex items-center gap-3 rounded-xl border border-slate-200/60 bg-slate-50 p-3"><label className="flex cursor-pointer items-center gap-2"><input type="checkbox" name="mesclarAssinatura" checked={formData.mesclarAssinatura !== false} onChange={handleChange} className="h-4 w-4 rounded text-pink-600" /><div><span className="block text-xs font-bold uppercase text-[#001a33]">Modo Mesclagem (Multiplicar)</span><span className="mt-0.5 block text-[8px] font-bold uppercase leading-none tracking-widest text-slate-400">Remove fundo branco da assinatura</span></div></label></div><div><label className="mb-1.5 flex justify-between text-[9px] font-bold uppercase tracking-widest text-slate-500"><span>Largura da Assinatura</span><span className="font-mono">{(formData.assinaturaDiretorWidth || 25).toFixed(1)}%</span></label><input type="range" name="assinaturaDiretorWidth" min="10" max="60" step="0.5" value={formData.assinaturaDiretorWidth || 25} onChange={(event) => setFormData({ ...formData, assinaturaDiretorWidth: Number.parseFloat(event.target.value) })} className="h-1 w-full cursor-pointer appearance-none rounded-lg bg-slate-250 accent-pink-600" /></div></div>}
        </div>
      )}
    </div>
  </>
);

export default CarteirinhaEditorBackIdentityPanel;
